"""Data models for security hypotheses generated by the agent reasoning layer."""

from dataclasses import dataclass, field
import json
from typing import List, Dict, Any, Optional


@dataclass
class EvidenceReference:
    """References specific evidence from an InspectionReport."""
    type: str  # e.g., "security_indicator", "route", "entry_point", "file"
    file: str
    line: Optional[int] = None
    detail: str = ""

    def to_dict(self) -> Dict[str, Any]:
        res = {
            "type": self.type,
            "file": self.file,
            "detail": self.detail
        }
        if self.line is not None:
            res["line"] = self.line
        return res


@dataclass
class SecurityHypothesis:
    """Represents a hypothesized security concern generated by the reasoning layer."""
    id: str  # Stable unique identifier
    title: str
    description: str
    category: str
    severity: str  # CRITICAL, HIGH, MEDIUM, LOW
    confidence: float
    evidence_references: List[EvidenceReference] = field(default_factory=list)
    rationale: str = ""
    affected_paths: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "title": self.title,
            "description": self.description,
            "category": self.category,
            "severity": self.severity,
            "confidence": round(self.confidence, 2),
            "evidence_references": [ref.to_dict() for ref in self.evidence_references],
            "rationale": self.rationale,
            "affected_paths": self.affected_paths,
            "metadata": self.metadata
        }


@dataclass
class ReasoningReport:
    """The result of the reasoning layer, containing a collection of security hypotheses."""
    hypotheses: List[SecurityHypothesis] = field(default_factory=list)
    validation_status: str = "success"  # success, partial_success, failed
    errors: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "hypotheses": [h.to_dict() for h in self.hypotheses],
            "validation_status": self.validation_status,
            "errors": self.errors
        }

    def to_json(self, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), indent=indent, allow_nan=False)


def generate_hypothesis_id(category: str, identity: Dict[str, Any], is_llm: bool = False) -> str:
    """Generates a stable, collision-resistant hypothesis ID using SHA-256."""
    import hashlib
    canonical = json.dumps(identity, sort_keys=True, separators=(",", ":"))
    digest = hashlib.sha256(canonical.encode("utf-8")).hexdigest()
    prefix = "HYP-LLM" if is_llm else "HYP"
    cat_prefix = f"{prefix}-{category.upper().replace('_', '-')}"
    return f"{cat_prefix}-{digest[:16]}"


